name = "GNNCellTypeReferenceGraph"
uuid = "4ca4c1c6-74a3-4c57-aa75-00a0b5a8f3e5"
authors = ["Chris Damour"]
version = "1.0.5"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExpressionData = "479be80e-0d6f-4501-bee0-9ae8a09d31d3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
OntologyTrees = "66aab7ce-4ed8-4c2b-b8f5-3ecb1547f657"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CondaPkg = "0.2"
Configurations = "0.17"
DataFrames = "1"
MetaGraphs = "0.7"
Preferences = "1"
RCall = "0.14"
Statistics = "1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
